### ISSUE TITLE
Light theme color is not same at all places.

### ISSUE THREAD

**Issue by aasutossh** [gruvbox-material/vscode#11]
It's a bit weird to explain, simply said, colors don't match everywhere.
Look at it in the following images.
![Screenshot from 2020-02-20 13-38-33](https://user-images.githubusercontent.com/18498932/74912495-ece16780-53e6-11ea-9eca-4933008285f4.png)
![Screenshot from 2020-02-20 13-35-47](https://user-images.githubusercontent.com/18498932/74912506-f36fdf00-53e6-11ea-84d8-49472caaebbf.png)
![Screenshot from 2020-02-20 13-35-44](https://user-images.githubusercontent.com/18498932/74912514-f965c000-53e6-11ea-8acb-236db8ad94e2.png)

Could my graphics driver cause this?
Using Nvidia Driver version 440.44 with pop os.

**Comment by aasutossh** [comment]
Other gruvbox themes looks the same as this, but not solarized light.

**Comment by sainnhe** [comment]
I have no idea what is going on, but I think this may not be caused by your graphics driver, because this phenomenon can be retained through screenshots.

If this bug can be reproduced in other ports of gruvbox theme, it is likely caused by vscode instead of theme extensions. Maybe you can open an issue in the repository of [vscode](https://github.com/Microsoft/vscode)

**Comment by aasutossh** [comment]
I am using [VSCodium](https://github.com/VSCodium/vscodium) if it matters.
I'll try it in VSCode to see if it occurs or not.

**Comment by aasutossh** [comment]
![Screenshot from 2020-02-20 15-17-55](https://user-images.githubusercontent.com/18498932/74920382-33898e80-53f4-11ea-95af-2adc430ac364.png)
Same thing in VSCode.
